### ISSUE TITLE
Settings file to pick which applications would be installed

### ISSUE THREAD

**Issue by valentin-nasta** [kurron/jvm-development-environment#9]
Is there a way to pick which application one wants to install without to check all ansible-pull-* repositories and comment code blocks?

**Comment by kurron** [comment]
I am sorry but there is not. Ansible does have a very limited user
interface so it might be possible but I like to have everything work
without human interaction.

Thanks,
Rin

**Comment by kurron** [comment]
I just looked in the Ansible documentation and I found was the ability to accept input, such as passwords, but nothing that might thought of as a basic menu system. It is an interesting idea but it smells like a fairly complex problem that I don't feel like solving right now.  What I might suggest is to adjust your copy of the `vagrantfile` and have it run only your custom plays.  That way, you are in complete control of what is installed.
